http:
  routers:
    my-routers:
      entryPoints:
        - http
      service: service-http
      rule: PathPrefix(`/`)
  services:
    service-http:
      loadBalancer:
        servers:
          - url: naver.com
