[http]

  # create router for http 
  [http.routers.my-routers]
    entryPoints = ["http"]
    service = "service-http" 
    rule = "PathPrefix(`/`)"
  
  # create load balancer for service-http
  [http.services]
    [http.services.service-http.loadBalancer]
      [[http.services.service-http.loadBalancer.servers]]
        url = "naver.com"  